version: '3'
services:
    app:
        # 起動イメージ
        image: node:18
        # 環境変数
        environment:
            - DATABASE_URL=postgresql://postgres:passw0rd@host.docker.internal:5432/postgres
        tty: true
        # ホスト側のポート：コンテナのポート
        ports:
            - '3001:3001'
        # ホスト側のsrcをコンテナのappにマウント
        volumes:
            - ./:/app
        # 起動時のカレントフォルダ
        working_dir: /app
        # 起動後に実行するコマンド
        command: sh -c 'npm run build; npm run start'